In [1]:
import tensorflow as tf
import numpy as np

C:\Users\msmar\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\msmar\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\msmar\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\msmar\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:
    indices = tf.constant([[0], [2]])
    updates = tf.constant([[[5, 5, 5, 5], [6, 6, 6, 6],
                            [7, 7, 7, 7], [8, 8, 8, 8]],
                           [[5, 5, 5, 5], [6, 6, 6, 6],
                            [7, 7, 7, 7], [8, 8, 8, 8]]])
    shape = tf.constant([4, 4, 4])
    scatter = tf.scatter_nd(indices, updates, shape)
    with tf.Session() as sess:
      print(sess.run(scatter))

[[[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [4]:
ref = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8])
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
add = tf.scatter_nd_add(ref, indices, updates)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(add))
    

[ 1 13  3 14 14  6  7 20]


In [5]:
np_matrix = np.random.rand(1,64,64,1)
#print matrix
#print range(8)
tf_tensors = tf.convert_to_tensor(np_matrix)
#for i in range(64):
tf_tensor = tf.gather_nd(tf_tensors, (0,8,56,0))
with tf.Session() as sess:
        vector = sess.run(tf_tensor)
        print(vector)

0.514429344091663


In [6]:
z = tf.convert_to_tensor(np.random.rand(8,64,64,2))
y = tf.convert_to_tensor(np.random.rand(1,64,64,1))
s = tf.size(y)
with tf.control_dependencies([tf.equal(z, 1)]):
    output = z
#while tf.equal(z,2):
    #x = z
with tf.Session() as sess:
    out,size = sess.run([output,s])
    print(size)

4096


In [7]:

with tf.Session() as sess:
    z = sess.run(tf.range(8))
    print(z[2])


2


In [8]:
print(64*64)

4096


In [10]:
for i in range(4,64-4,4):
    print(i)
print(len(range(4,64-4,4)))

4
8
12
16
20
24
28
32
36
40
44
48
52
56
14


In [11]:
i = tf_tensors = tf.convert_to_tensor(np.array([2,3,4,6]))
j = tf.convert_to_tensor(np.array([1,2,3,4]))
h= tf.reduce_sum(tf.square(tf.subtract(i, j)))
i=1.0
j=2
h= tf.div(i, j)
#h= i+j
with tf.Session() as sess:
    z = sess.run(h)
    print(z)

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
0.5


In [12]:
for y in range(100,450,64):
    print(y)
    

100
164
228
292
356
420
